name: botCoinbase
description: A sample command-line application.
version: 1.0.0
publish_to:  none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mercury_client: ^2.0.2
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
